name: routy
description: "Application de gestion des ventes, livraison et facturation - Application terrain pour vendeurs et livreurs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Navigation
  go_router: ^14.6.2
  flutter_svg: ^2.0.10+1

  # Charts & Animations
  fl_chart: ^0.69.0
  shimmer: ^3.0.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  path: ^1.9.0
  wakelock_plus: ^1.4.0
  logger: ^2.5.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Location & Maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  
  # Printing & PDF
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
    - assets/logo/
  
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Cairo-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  
  generate: true
