// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sale_order_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SaleOrderModel _$SaleOrderModelFromJson(Map<String, dynamic> json) =>
    SaleOrderModel(
      id: (json['id'] as num?)?.toInt(),
      odooId: (json['odooId'] as num?)?.toInt(),
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
      synced: json['synced'] as bool? ?? false,
      syncStatus:
          $enumDecodeNullable(_$SyncStatusEnumMap, json['syncStatus']) ??
          SyncStatus.pending,
      name: json['name'],
      displayName: json['display_name'],
      state: json['state'],
      invoiceStatus: json['invoice_status'],
      partnerId: json['partner_id'],
      partnerInvoiceId: json['partner_invoice_id'],
      partnerShippingId: json['partner_shipping_id'],
      dateOrder: json['date_order'],
      validityDate: json['validity_date'],
      commitmentDate: json['commitment_date'],
      confirmationDate: json['confirmation_date'],
      expectedDate: json['expected_date'],
      effectiveDate: json['effective_date'],
      amountUntaxed: json['amount_untaxed'],
      amountTax: json['amount_tax'],
      amountTotal: json['amount_total'],
      margin: json['margin'],
      pricelistId: json['pricelist_id'],
      currencyId: json['currency_id'],
      paymentTermId: json['payment_term_id'],
      fiscalPositionId: json['fiscal_position_id'],
      orderLine: json['order_line'],
      note: json['note'],
      reference: json['reference'],
      clientOrderRef: json['client_order_ref'],
      origin: json['origin'],
      userId: json['user_id'],
      teamId: json['team_id'],
      companyId: json['company_id'],
      pickingIds: json['picking_ids'],
      deliveryCount: json['delivery_count'],
      warehouseId: json['warehouse_id'],
      pickingPolicy: json['picking_policy'],
      incoterm: json['incoterm'],
      invoiceCount: json['invoice_count'],
      moveIds: json['move_ids'],
      saleOrderTemplateId: json['sale_order_template_id'],
      saleOrderOptionIds: json['sale_order_option_ids'],
      requireSignature: json['require_signature'],
      requirePayment: json['require_payment'],
      signedBy: json['signed_by'],
      signedOn: json['signed_on'],
      signature: json['signature'],
      analyticAccountId: json['analytic_account_id'],
      campaignId: json['campaign_id'],
      mediumId: json['medium_id'],
      sourceId: json['source_id'],
      expenseCount: json['expense_count'],
      authorizedTransactionIds: json['authorized_transaction_ids'],
      lastUpdate: json['__last_update'],
      messageFollowerIds: json['message_follower_ids'],
      activityIds: json['activity_ids'],
      messageIds: json['message_ids'],
      messageAttachmentCount: json['message_attachment_count'],
    );

Map<String, dynamic> _$SaleOrderModelToJson(SaleOrderModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'odooId': instance.odooId,
      'createdAt': instance.createdAt?.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
      'synced': instance.synced,
      'syncStatus': _$SyncStatusEnumMap[instance.syncStatus]!,
      'name': instance.name,
      'display_name': instance.displayName,
      'state': instance.state,
      'invoice_status': instance.invoiceStatus,
      'partner_id': instance.partnerId,
      'partner_invoice_id': instance.partnerInvoiceId,
      'partner_shipping_id': instance.partnerShippingId,
      'date_order': instance.dateOrder,
      'validity_date': instance.validityDate,
      'commitment_date': instance.commitmentDate,
      'confirmation_date': instance.confirmationDate,
      'expected_date': instance.expectedDate,
      'effective_date': instance.effectiveDate,
      'amount_untaxed': instance.amountUntaxed,
      'amount_tax': instance.amountTax,
      'amount_total': instance.amountTotal,
      'margin': instance.margin,
      'pricelist_id': instance.pricelistId,
      'currency_id': instance.currencyId,
      'payment_term_id': instance.paymentTermId,
      'fiscal_position_id': instance.fiscalPositionId,
      'order_line': instance.orderLine,
      'note': instance.note,
      'reference': instance.reference,
      'client_order_ref': instance.clientOrderRef,
      'origin': instance.origin,
      'user_id': instance.userId,
      'team_id': instance.teamId,
      'company_id': instance.companyId,
      'picking_ids': instance.pickingIds,
      'delivery_count': instance.deliveryCount,
      'warehouse_id': instance.warehouseId,
      'picking_policy': instance.pickingPolicy,
      'incoterm': instance.incoterm,
      'invoice_count': instance.invoiceCount,
      'move_ids': instance.moveIds,
      'sale_order_template_id': instance.saleOrderTemplateId,
      'sale_order_option_ids': instance.saleOrderOptionIds,
      'require_signature': instance.requireSignature,
      'require_payment': instance.requirePayment,
      'signed_by': instance.signedBy,
      'signed_on': instance.signedOn,
      'signature': instance.signature,
      'analytic_account_id': instance.analyticAccountId,
      'campaign_id': instance.campaignId,
      'medium_id': instance.mediumId,
      'source_id': instance.sourceId,
      'expense_count': instance.expenseCount,
      'authorized_transaction_ids': instance.authorizedTransactionIds,
      '__last_update': instance.lastUpdate,
      'message_follower_ids': instance.messageFollowerIds,
      'activity_ids': instance.activityIds,
      'message_ids': instance.messageIds,
      'message_attachment_count': instance.messageAttachmentCount,
    };

const _$SyncStatusEnumMap = {
  SyncStatus.pending: 'pending',
  SyncStatus.syncing: 'syncing',
  SyncStatus.synced: 'synced',
  SyncStatus.failed: 'failed',
  SyncStatus.conflict: 'conflict',
};
